framework:
    messenger:
        default_bus: command.bus
        serializer:
            # default_serializer: messenger.transport.native_php_serializer => Basic from php (serialize/unserialize)
            default_serializer: Shared\Infrastructure\Symfony\Bus\Serializer\SymfonyMessageSerializer
        transports:
            redis-async:
                dsn: '%env(REDIS_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000        # millisecond
                    multiplier: 2      # Exponential backoff
                    max_delay: 10000   # 10 secs max
            rabbitmq-async:
                dsn: '%env(RABBIT_TRANSPORT_DSN)%'
                serializer: 'Shared\Infrastructure\Symfony\Bus\Serializer\DomainEventSerializer'
                options:
                    auto_setup: true  # Allow Messenger to create delay/retry exchanges
                    exchange:
                        name: 'domain_events'
                        type: 'topic'
                    # Define queues that consumers can subscribe to
                    # Each queue is bound with its eventName() as routing key
                    queues:
                        ingestor.event.created:
                            binding_keys: ['ingestor.event.created']
                        # Add more queues here as you create new events:
                        # ingestor.event.deleted:
                        #     binding_keys: ['ingestor.event.deleted']
                        # ingestor.event.postponed:
                        #     binding_keys: ['ingestor.event.postponed']
                retry_strategy:
                    max_retries: 3
                    delay: 2000
                    multiplier: 2
                    max_delay: 30000

            # TODO: implement this
            failed: 'doctrine://default?queue_name=failed'
        routing:
            # Sends events from the IngestEventCommandHandler to the redis instance, to be processed asynchronously
            'Ingestor\Application\IngestEventMessage': redis-async

            # Routes all DomainEvents to RabbitMQ
            'Shared\Domain\Event\DomainEvent': rabbitmq-async
        buses:
            command.bus:
            query.bus:
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
