# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    SymfonyClient\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    # Controllers are imported separately to allow attributes
    SymfonyClient\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    Shared\:
        resource: '../../../src/Shared/'

    Catalog\:
        resource: '../../../src/Catalog/'

    Ingestor\:
        resource: '../../../src/Ingestor/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Ingestor\Infrastructure\Http\HttpEventsProviderClient:
        arguments:
            $baseUrl: '%env(EXTERNAL_PROVIDER_BASE_URL)%'

    Shared\Infrastructure\Symfony\Command\RabbitMQSetupQueuesCommand:
        arguments:
            $projectDir: '%kernel.project_dir%/../../'
            $rabbitHost: '%env(RABBITMQ_HOST)%'
            $rabbitPort: '%env(RABBITMQ_PORT)%'
            $rabbitUser: '%env(RABBITMQ_USER)%'
            $rabbitPassword: '%env(RABBITMQ_PASSWORD)%'
            $rabbitVhost: '%env(RABBITMQ_VHOST)%'
        tags: ['console.command']

    Shared\Application\Bus\Message\MessageBus:
        '@Shared\Infrastructure\Symfony\Bus\Message\SymfonyMessageBus'

    Shared\Application\Bus\Event\EventBus:
        '@Shared\Infrastructure\Symfony\Bus\Event\SymfonyEventBus'

    Shared\Infrastructure\Symfony\Bus\Event\SymfonyEventBus:
        arguments:
            $eventBus: '@event.bus'

    Shared\Infrastructure\Symfony\Bus\Query\SymfonyQueryBus:
        arguments:
            $bus: '@query.bus'

    Shared\Infrastructure\Symfony\Controller\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onException }

    Shared\Infrastructure\Symfony\Messenger\Transport\RedisJsonTransportFactory:
        tags:
            - { name: messenger.transport_factory }

    Shared\Infrastructure\Symfony\Messenger\Transport\AutoDiscoveryAmqpTransportFactory:
        arguments:
            $projectDir: '%kernel.project_dir%/../../'
        tags:
            - { name: messenger.transport_factory, priority: 10 }

    _instanceof:
        Shared\Application\Bus\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        Shared\Application\Bus\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }
        Shared\Application\Bus\Event\EventSubscriber:
            tags:
                - { name: messenger.message_handler }
