# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    SymfonyClient\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    # Controllers are imported separately to allow attributes
    SymfonyClient\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    Shared\:
        resource: '../../../src/Shared/'
        exclude:
            - '../../../src/Shared/Infrastructure/Persistence/migrations'

    Catalog\:
        resource: '../../../src/Catalog/'

    Ingestor\:
        resource: '../../../src/Ingestor/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # ##############################
    # Project specific dependencies
    # ##############################
    Ingestor\Infrastructure\Http\HttpEventsProviderClient:
        arguments:
            $baseUrl: '%env(EXTERNAL_PROVIDER_BASE_URL)%'

    Catalog\Update\Infrastructure\Persistence\OpenSearchCatalogWriter:
        arguments:
            $client: '@opensearch.client'

    # ########################################
    # Shared dependencies for all the project
    # ########################################
    Shared\Infrastructure\Symfony\Command\RabbitMQSetupQueuesCommand:
        arguments:
            $eventSubscribers: !tagged_iterator domain.event.subscriber
            $rabbitHost: '%env(RABBITMQ_HOST)%'
            $rabbitPort: '%env(RABBITMQ_PORT)%'
            $rabbitUser: '%env(RABBITMQ_USER)%'
            $rabbitPassword: '%env(RABBITMQ_PASSWORD)%'
            $rabbitVhost: '%env(RABBITMQ_VHOST)%'
        tags: ['console.command']

    Shared\Infrastructure\Symfony\Command\OpenSearchSetupCommand:
        arguments:
            $client: '@opensearch.client'
        tags: ['console.command']

    opensearch.client:
        class: OpenSearch\Client
        factory: '@shared.infrastructure.persistence.opensearch.opensearch_client_factory'

    shared.infrastructure.persistence.opensearch.opensearch_client_factory:
        class: Shared\Infrastructure\Persistence\OpenSearch\OpenSearchClientFactory
        arguments:
            $host: '%env(OPENSEARCH_HOST)%'
            $port: '%env(OPENSEARCH_PORT)%'
            $user: '%env(OPENSEARCH_ADMIN_USER)%'
            $password: '%env(OPENSEARCH_ADMIN_PASSWORD)%'

    Shared\Application\Bus\Message\MessageBus:
        '@Shared\Infrastructure\Symfony\Bus\Message\SymfonyMessageBus'

    Shared\Application\Bus\Event\EventBus:
        '@Shared\Infrastructure\Symfony\Bus\Event\SymfonyEventBus'

    Shared\Infrastructure\Symfony\Bus\Event\SymfonyEventBus:
        arguments:
            $eventBus: '@event.bus'

    Shared\Infrastructure\Symfony\Command\OutboxRelayCommand:
        arguments:
            $eventBus: '@event.bus'
        tags: ['console.command']

    Shared\Infrastructure\Symfony\Bus\Query\SymfonyQueryBus:
        arguments:
            $bus: '@query.bus'

    Shared\Infrastructure\Symfony\Controller\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onException }

    Shared\Infrastructure\Symfony\Messenger\Transport\RedisJsonTransportFactory:
        tags:
            - { name: messenger.transport_factory }

    Shared\Infrastructure\Symfony\Messenger\Transport\AutoDiscoveryAmqpTransportFactory:
        arguments:
            $mapping: !tagged_iterator domain.event.subscriber
        tags:
            - { name: messenger.transport_factory, priority: 10 }

    _instanceof:
        Shared\Application\Bus\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        Shared\Application\Bus\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }
        Shared\Application\Bus\Event\EventSubscriber:
            tags:
                - { name: messenger.message_handler }
                - 'domain.event.subscriber'
